### ISSUE TITLE
View only access to reports folder on Google Drive

### ISSUE THREAD

**Issue by DainialPadraig** [GDGNorthAmerica/info-and-resources#2]
I'm unable to upload event reports to the I/O Extended 2017 reports folder because the link is for view only access. Link permissions need to be changed.

**Comment by Splaktar** [comment]
Please contact @nyener or @momander about this issue. Is it the link from the organizer guide or an email?

**Comment by nyener** [comment]
You can edit the folder now @Splaktar @DainialPadraig
